name: Test Custom Node.js Docker Action
 
on:
  workflow_dispatch:
 
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
 
      - name: Run custom Node.js Docker Action
        uses: ./   # use local action
        with:
          who-to-greet: # id of input
